// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBAu-PvCZLc_nuPpQUYdjsZH5vwzfkDGsA",
    appId: "1:936846897668:web:fcaabbc6073a0c4a383b51",
    messagingSenderId: "936846897668",
    projectId: "afronex-shop",
    authDomain: "afronex-shop.firebaseapp.com",
    storageBucket: "afronex-shop.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBOCgoOE7oCTSsAEf48mN57aM7eCoF9vQ0",
    appId: "1:936846897668:android:39df679f6149ba0f383b51",
    messagingSenderId: "936846897668",
    projectId: "afronex-shop",
    storageBucket: "afronex-shop.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBpNPVFDC0Vpj73aX6B7haxq7AfS0eVK3M",
    appId: "1:936846897668:ios:83e5cca8edb5eb5e383b51",
    messagingSenderId: "936846897668",
    projectId: "afronex-shop",
    storageBucket: "afronex-shop.appspot.com",
    iosBundleId: "com.example.afronexShopApp",
  );
}
